# Generated by Django 4.0.1 on 2022-01-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='enrolled_students_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='maximum_number_of_students',
            field=models.IntegerField(default=50),
        ),
    ]
