# Generated by Django 4.0.1 on 2022-01-19 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0003_school_enrolled_students_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
