# Generated by Django 3.2.11 on 2022-01-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0005_school_updated_student_updated_alter_school_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='enrolled_students_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
